apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomize
  name: kustomize-svc
spec:
  ports:
  - name: nginx-svc
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: kustomize
  type: NodePort